version: "3.8"
####################################
#RENAME CONTAINER TO THE SERVICENAME
####################################
####################################
####################################
####################################
####################################
networks:
  inception:
    name: inception

services:
  nginx_service:
    container_name: nginx_container
    build: ./requirements/nginx/.
    image: nginx_image
    ports: 
      - "443:443"
    networks: 
      - inception
    volumes:
      - /home/aestraic/data/wordpress:/usr/share/nginx/html
    restart: unless-stopped
    env_file: .env

  mariadb_service:
    container_name: mariadb_container
    hostname: mariadb_container
    build: ./requirements/mariadb/.
    image: mariadb_image
    ports: 
      - "3306:3306"
    networks: 
      - inception
    volumes:
      - /home/aestraic/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    # depends_on:

  wp_service:
    container_name: wp_container
    build: ./requirements/wordpress/.
    image: wp_image
    ports: 
      - "9000:9000"
    networks: 
      - inception
    env_file: .env
    restart: unless-stopped
    volumes:
      - /home/aestraic/data/wordpress:/wp
    # depends_on:
      # - mariadb_service
      # - nginx_service