version: "3.8"

networks:
  inception:
    name: Inception

services:
  nginx_service:
    container_name: nginx_container
    build: ./requirements/nginx/.
    image: nginx_image
    ports:
     - "443:443"
    networks:
     - inception
    env_file:
     - .env

