version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx_image
    ports: 
      - "443:443"
    networks: 
      - inception
    volumes:
      - v_wordpress:/usr/share/nginx/html
    restart: unless-stopped
    env_file: .env

  mariadb:
    container_name: mariadb
    hostname: mariadb_container
    build: ./requirements/mariadb/.
    image: mariadb_image
    ports: 
      - "3306:3306"
    networks: 
      - inception
    volumes:
      - v_mariadb:/var/lib/mysql
    restart: unless-stopped
    env_file: .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wp_image
    ports: 
      - "9000:9000"
    networks: 
      - inception
    volumes:
      - v_wordpress:/wp
    restart: unless-stopped
    env_file: .env

volumes:
  v_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/aestraic/data/wordpress
      o: bind
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      device:  /home/aestraic/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge