version: "3.8"

networks:
  inception:
    name: Inception

services:
  nginx_service:
    container_name: nginx_container
    build: ./requirements/nginx/.
    image: nginx_image
    ports: 
      - "443:443"
    networks: 
      - inception
    volumes:
      - /home/aestraic/data/wordpress:/usr/share/nginx/html
    env_file: .env

  mariadb_service:
    container_name: mariadb_container
    hostname: mariadb_container
    build: ./requirements/mariadb/.
    image: mariadb_image
    ports: 
      - "3306:3306"
    networks: 
      - inception
    volumes:
      - /home/aestraic/data/mariadb:/var/lib/mysql
    env_file: .env
    # depends_on:

  wp_service:
    container_name: wp_container
    build: ./requirements/wordpress/.
    image: wp_image
    ports: 
      - "8080:80"
    networks: 
      - inception
    env_file: .env
    volumes:
      - /home/aestraic/data/wordpress:/wp
    # depends_on:
      # - mariadb_service
      # - nginx_service